services:
#  traefik:
#    container_name: traefik
#    image: traefik:v3.0
#    ports:
#      - "80:80"
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#      - ./configs/traefik:/etc/traefik
#      - ./configs/traefik:/acme.json
#    depends_on:
#      - deliver-service
#      - payments-service
#      - punishments-service
#    networks:
#      - traefik

#  frontend:
#    container_name: frontend
#    build:
#      context: ./frontend
#      dockerfile: Dockerfile
#    networks:
#      - traefik

#  notifications-service:
#    container_name: notifications
#    user: root
#    build:
#      context: ./api/notifications-service
#      dockerfile: ./deploy/Dockerfile
#    depends_on:
#      - kafka-1
#    networks:
#      - traefik
#
#  deliver-service:
#    container_name: deliver
#    user: root
#    build:
#      context: ./api/deliver-service
#      dockerfile: ./deploy/Dockerfile
#    depends_on:
#      - kafka-ui
#    networks:
#      - traefik

#  payments-service:
#    user: root
#    container_name: payments
#    expose:
#      - 9092
#    build:
#      context: ./api/payments-service
#      dockerfile: ./deploy/Dockerfile
#    depends_on:
#      - kafka-ui
#    networks:
#      - traefik

#  punishments-service:
#    container_name: punishments-service
#    user: root
#    build:
#      context: ./api/punishments-service
#      dockerfile: ./deploy/Dockerfile
#    depends_on:
#      - mysql
#    networks:
#      - traefik

  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - traefik

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka-1:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    depends_on:
      - zookeeper
      - kafka-1
    networks:
      - traefik

  kafka-1:
    image: wurstmeister/kafka
    ports:
      - "9095:9094"
    expose:
      - 9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://kafka-1:9092,OUTSIDE://kafka-1:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:9092,OUTSIDE://localhost:9095
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT

      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_BROKER_ID: 500
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./configs/kafka-data/500:/kafka
    depends_on:
      - zookeeper
    networks:
      - traefik

#  mysql:
#    container_name: mysql
#    image: mysql:oraclelinux9
#    environment:
#      MYSQL_DATABASE: ${MYSQL_DATABASE}
#      MYSQL_USER: ${MYSQL_USER}
#      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
#      MYSQL_ALLOW_EMPTY_PASSWORD: false
#    networks:
#      - traefik
#    volumes:
#      - ./configs/mysql/data:/var/lib/mysql/

networks:
  traefik:
    name: traefik-network
    driver: bridge