// Code generated by mockery v2.49.2. DO NOT EDIT.

package mocks

import (
	context "context"
	entities "jwt-auth-service/internal/entities"

	mock "github.com/stretchr/testify/mock"
)

// AuthPostgresRepository is an autogenerated mock type for the AuthPostgresRepository type
type AuthPostgresRepository struct {
	mock.Mock
}

// RemoveToken provides a mock function with given fields: ctx, refreshToken
func (_m *AuthPostgresRepository) RemoveToken(ctx context.Context, refreshToken string) error {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RemoveToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetToken provides a mock function with given fields: ctx, userId, session
func (_m *AuthPostgresRepository) SetToken(ctx context.Context, userId string, session *entities.Session) error {
	ret := _m.Called(ctx, userId, session)

	if len(ret) == 0 {
		panic("no return value specified for SetToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *entities.Session) error); ok {
		r0 = rf(ctx, userId, session)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAuthPostgresRepository creates a new instance of AuthPostgresRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthPostgresRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthPostgresRepository {
	mock := &AuthPostgresRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
